---
title: "Day 3"
---


## Part I

```{r part1}

library(pacman)
p_load(stringr, dplyr)

df <- readLines("day3/input.txt")

pad <- function(in_data){
  padded_rows <- c(str_c(rep(".",nchar(in_data[1])),collapse=""), 
              in_data, 
              str_c(rep(".",nchar(in_data[1])),collapse=""))
  
  padded_columns <- str_c(".",padded_rows,".")
  
  return(padded_columns)
}

df <- pad(df)

#all_signs <- names(table(df_mat))
#specials <- str_c(all_signs, collapse="|\\")

specials <- "\\-|\\#|\\$|\\%|\\&|\\*|\\/|\\@|\\+|\\="

df <- str_replace_all(df, specials, "#")

df_in <- df

sum <- 0

for(row_search in 1:length(df_in)){
hm <- unlist(str_extract_all(df_in[row_search], "\\d+"))
  
   #hm is 2 places long, so loop the below for each item in hm. 
    for(i in seq_along(hm)){
    loc <- str_locate(df_in[row_search], hm[i])
    
    line1 <- substr(df_in[row_search-1],(loc[1]-1), (loc[2]+1))
    line2 <- substr(df_in[row_search],(loc[1]-1), (loc[2]+1))
    line3 <- substr(df_in[row_search+1],(loc[1]-1), (loc[2]+1))
    
    search_around <- str_c(line1, line2, line3) 
    
    if(str_detect(search_around, "\\#") == TRUE){
      sum <- sum + as.numeric(hm[i])
    } else {
      sum <- sum
    }
    df_in[row_search] <- str_replace(df_in[row_search], hm[i], strrep(".",times=nchar(hm[i])))
  }
}

sum # correct answer

```


## Part II

```{r}

df <- readLines("day3/input.txt")

pad <- function(in_data){
  padded_rows <- c(str_c(rep(".",nchar(in_data[1])),collapse=""), 
              in_data, 
              str_c(rep(".",nchar(in_data[1])),collapse=""))
  
  padded_columns <- str_c(".",padded_rows,".")
  
  return(padded_columns)
}

df <- pad(df)

df_in <- df

sum <- 0

df_new <- data.frame(value=0, star_row=NA, star_col=NA)
df_fun <- data.frame(value=0, star_row=NA, star_col=NA)

for(row_search in 1:142){
hm <- unlist(str_extract_all(df_in[row_search], "\\d+"))
  if(length(hm) == 0) next
   #hm is 2 places long, so loop the below for each item in hm. 
    for(i in 1:length(hm)){
    loc <- str_locate(df_in[row_search], hm[i])
    
    line1 <- substr(df_in[row_search-1],(loc[1]-1), (loc[2]+1))
    line2 <- substr(df_in[row_search],(loc[1]-1), (loc[2]+1))
    line3 <- substr(df_in[row_search+1],(loc[1]-1), (loc[2]+1))
    
    search_around <- str_c(line1, line2, line3) 
  
    if(str_detect(search_around, "\\*") == TRUE){
      if(str_detect(line1, "\\*") == T){
        df_fun$star_row <- row_search-1
      } else if (str_detect(line2, "\\*") == T){
        df_fun$star_row <- row_search
      } else if (str_detect(line3, "\\*") == T){
        df_fun$star_row <- row_search+1
      }
      
      col_step <- c(loc[1]+str_locate(line1, "\\*")[1]-2,
      loc[1]+str_locate(line2, "\\*")[1]-2,
      loc[1]+str_locate(line3, "\\*")[1]-2)
      

      df_fun$star_col <- col_step[which(!is.na(col_step))]
      
      df_fun$value <- as.numeric(hm[i])
      df_new <- rbind(df_new, df_fun)
    } else {
      #sum <- sum
    }
    df_in[row_search] <- str_replace(df_in[row_search], hm[i], strrep(".",times=nchar(hm[i])))
  }
}

summing_up <- df_new %>% group_by(star_row, star_col) %>% summarise(product = prod(value), n=n()) %>% filter(n == 2)

sum(summing_up$product) # correct answer, omfg


```





